### ISSUE TITLE
[Bug]: command test-storybook fails with yarn-berry

### ISSUE THREAD

**Issue by atarek12** [storybookjs/test-runner#492]
### Describe the bug

I got this error while trying to run `yarn test-storybook`

```text
Test suite failed to run

    TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function

      at node_modules/@storybook/test-runner/dist/index.js:13506:48
          at Array.reduce (<anonymous>)
      at transformCsf (node_modules/@storybook/test-runner/dist/index.js:13500:41)
      at transformPlaywright (node_modules/@storybook/test-runner/dist/index.js:13627:18)
      at Object.process (node_modules/@storybook/test-runner/playwright/transform.js:6:21)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:545:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:674:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:726:19)
```

### To Reproduce

When running `yarn test-storybook`, I got the error on each story file.
I have tried to run it against all browsers (chromium, firefox, webkit), but all gives the same error

the error occurs locally and on github action too, here is my workflow file

```yml
name: Run Tests on PR

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.0'

      - name: Instal Dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: yarn build-storybook --quiet

      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && yarn test-storybook"

```

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Binaries:
    Node: 20.11.1 - C:\Users\AHMEDT~1\AppData\Local\Temp\xfs-acc53f4e\node.CMD
    Yarn: 4.3.0 - C:\Users\AHMEDT~1\AppData\Local\Temp\xfs-acc53f4e\yarn.CMD <----- active
    npm: 10.2.4 - ~\.nvm\versions\node\v20.11.1\bin\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.87)
  npmPackages:
    @storybook/addon-a11y: ^8.1.11 => 8.1.11
    @storybook/addon-actions: ^8.1.11 => 8.1.11
    @storybook/addon-designs: ^8.0.2 => 8.0.2
    @storybook/addon-essentials: ^8.1.11 => 8.1.11
    @storybook/addon-interactions: ^8.1.11 => 8.1.11
    @storybook/addon-links: ^8.1.11 => 8.1.11
    @storybook/addon-onboarding: ^8.1.11 => 8.1.11
    @storybook/blocks: ^8.1.11 => 8.1.11
    @storybook/react: ^8.1.11 => 8.1.11
    @storybook/react-vite: ^8.1.11 => 8.1.11
    @storybook/test: ^8.1.11 => 8.1.11
    @storybook/test-runner: ^0.19.0 => 0.19.0
    chromatic: ^11.4.0 => 11.4.0
    eslint-plugin-storybook: ^0.8.0 => 0.8.0
    storybook: ^8.1.11 => 8.1.11
    storybook-addon-performance: ^0.17.3 => 0.17.3
```
