### ISSUE TITLE
How do we use stories.json on Chromatic?

### ISSUE THREAD

**Issue by hayata-yamamoto** [storybookjs/test-runner#83]
## Question 

How to use chromatic stories.json in GitHub Actions with test-runner?

## Background 

Our storybooks are hosted on chromatic, then we're aiming to execute interaction test in GitHub Actions by using Chromatic hosting stories.json. However, we cannot pass through authentication by this test-runner. I've tried like this 

```bash
$ REFERENCE_URL=<chromatic-permalink> TARGET_URL=<chromatic-permalink> yarn test-storybook 
```

Cited from https://github.com/storybookjs/test-runner#2-running-against-locally-built-storybooks-in-ci

> NOTE: Building Storybook locally makes it simple to test Storybooks that could be available remotely, but are under authentication layers. If you also deploy your Storybooks somewhere (e.g. Chromatic, Vercel, etc.), the Storybook URL can still be useful with the test-runner. You can pass it to the REFERENCE_URL environment variable when running the test-storybook command, and if a story fails, the test-runner will provide a helpful message with the link to the story in your published Storybook instead.

**Comment by yannbf** [comment]
Hey @hayata-yamamoto, thanks for using this library!

Generally you might not need to use the library in conjunction with Chromatic because Chromatic is a test-runner that will provide you a similar experience automatically. Can you explain your use case? I'm quite interested.

I think it's nice to be able to run the test-runner as a required step **before** running Chromatic, so that if there are failures you don't end up making unnecessary Chromatic builds, and if everything passes you will be sure Chromatic will build successfully.

Still, to answer your question, you would need to do something like this:

1 - If your Chromatic is private, you can't bypass the authentication. You need a script to build the project and run the tests against it locally (no need for stories json mode this way). Follow [this](https://github.com/storybookjs/test-runner#2-running-against-locally-built-storybooks-in-ci) for more details.

2 - Add a new step after Chromatic finishes publishing Storybook

```yml
# chromatic.yml
on: push

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to retrieve git history
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      - name: Run storybook tests
        run: 'REFERENCE_URL=${{ steps.chromatic-publish.outputs.storybookUrl}} yarn test-storybook:ci'
```

The step will build and run tests against a local Storybook, but if there are errors it will use the REFERENCE_URL which will have the correct Chromatic link.

If your Chromatic is public, then you don't need to do step 1 and your `run` command would just be:

```sh
TARGET_URL=${{ steps.chromatic-publish.outputs.storybookUrl}} yarn test-storybook --stories-json
```
